//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETSAFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Réponse
    {
        public int id_reponse { get; set; }
        public int id_question { get; set; }
        public string texte { get; set; }
        public bool est_correct { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
