//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETSAFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur_Quiz
    {
        public int id_utilisateur { get; set; }
        public int id_quiz { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<System.DateTime> date_participation { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
